### ISSUE TITLE
고파스 로그인

### ISSUE THREAD

**Issue by youngsupchoi** [KU-niverse/ASKu-api#142]
**Description**
기존 로그인, 회원가입등의 기능을 고파스 회원가입, 로그인으로 연동

**Todo**
- [x] DB 불필요한 데이터 제거 및 새로운 데이터베이스 생성
- [x] user/auth/signup api수정
- [x] user/auth/signin api수정
- [x] user/mypage/info수정
- [x] 비밀번호 변경 버튼 제거
- [x] 마이페이지 보여주는 정보 수정
- [x] 아이디/비밀번호 찾기, 회원가입 버튼 고파스 링크로 라우트
- [x] 회원가입 ui수정
- [x] 서버 .env 파일 database변수 변경

**Etc**
기타사항
