### ISSUE TITLE
고파스 로그인 개인정보 수집 동의

### ISSUE THREAD

**Issue by youngsupchoi** [KU-niverse/ASKu-api#150]
**Description**
 - 기존 로그인은 만약 이전에 로그인한 기록이 있다면 로그인을 진행하고 해당 기록이 없다면 자동으로 유저를 등록하고 로그인을 진행, 하지만 프론트에서 로그인 했을 때 이전에 로그인한 기록이 없다면 해당 유저에게 동의를 받은 후 등록해야함 

**Todo**
- [x] 기존 로그인 api에서 유저가 접근 이력이 없을시 success = false, status = 402를 반환하고 유저의 nickname과 uuid를 반환
- [x] 회원가입 api에서 nickname과 uuid를 받아서 해당 유저를 등록
- [ ] uuid가 들어왔을때 해당 uuid가 유효한지 판단하고 유효하다면 로그인 상태를 반환
- [x] 회원가입시 등록 후 로그인 상태를 반환
- [ ] signup/koreapas api 스웨거 작성
- [ ] signin api 스웨거 수정

**Etc**
기타사항
