### ISSUE TITLE
dupcheck관련 api에서 중복체크시 삭제된 유저 제외

### ISSUE THREAD

**Issue by youngsupchoi** [KU-niverse/ASKu-api#40]
**Description**
유저중복체크 api에서 삭제된 유저의 닉네임, 이메일, 아이디를 제외하고 체크하지 않고 있습니다.

**Todo**
 - [ ] /user/auth/nickdupcheck/{nick}
 - [ ] /user/auth/iddupcheck/{loginid}
 - [ ] /user/auth/emaildupcheck/{email}

**Etc**
사실 이것을 고쳐도근본적으로 문제가 있습니다. 
유저가 회원탈퇴를 한 뒤 다시 같은 정보로 회원가입을 할 경우에 회원가입이 불가능합니다.
(email, login_id, nickname이 unique로 설정되어 있습니다)
