### ISSUE TITLE
배지 부여/회수 구현

### ISSUE THREAD

**Issue by starcat37** [KU-niverse/ASKu-api#47]
**Description**
배지를 부여/회수하는 로직을 구현합니다.

**Todo**
- [x] 배지 부여 로직 구현 - mysql trigger 사용, user_action에 update 발생할 때마다 체크
- [x] 배지 회수 로직 구현 - badge.js 미들웨어 사용, PUT /report/check에서 신고가 승인될 경우 신고 사유에 해당하는 히스토리 확인 후 배지 획득에 필요한 수치를 넘지 않을 경우 배지 회수 -> 신고 승인 시 해당 히스토리 is_bad 처리 -> user_action 재계산 후 기준 미충족 시 배지 회수
- [x] 정상 작동 확인
- [x] swagger 적합하게 수정 

**Etc**
좀 오래 걸릴 수도 있습니다😿
